/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagsColorFilesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// locales-list.ts
var import_obsidian = require("obsidian");

// locales/en.ts
var en_default = {
  SETTINGS_TITLE: "Tags Color Files settings",
  PLUGIN_DESCRIPTION: "This plugin allows you to highlight files in Obsidian file explorer based on the rules predefined by you. When you add a tag that has a corresponding coloring rule to a file, the plugin automatically highlights that file in the file explorer with predefined color and in the style of your choice.",
  GENERAL_SECTION: "General",
  COLOR_METHOD_NAME: "Coloring method",
  COLOR_METHOD_DESC: 'If any of the "Dots..." methods selected, multiple colored dots will be displayed simultaneously if the file has more than one tag with predefined coloring rule.',
  COLOR_TEXT: "Text",
  COLOR_BG: "Background",
  COLOR_DOTS_BEFORE: "Dots before text",
  COLOR_DOTS_AFTER: "Dots after text",
  COLOR_DOTS_BEFORE_TEXT: "Dots before text + text",
  COLOR_DOTS_AFTER_TEXT: "Dots after text + text",
  BACKUP_RESTORE: "Backup & restore",
  DOT_SIZE_NAME: "Dots size",
  DOT_SIZE_DESC: 'Choose the size of the dots for "Dots..." coloring methods.',
  DOT_SMALL: "Small",
  DOT_DEFAULT: "Default",
  DOT_BIG: "Big",
  EXPORT: "Export settings",
  IMPORT: "Import settings",
  EXPORTED: "Exported successfully!",
  IMPORTED: "Imported successfully!",
  INVALID_FILE: "Error: Invalid file",
  COLORING_RULES_SECTION: "Coloring rules",
  ADD_RULE_DESC: "General rules apply to all notes in the vault, folder rules apply to files in a specified folder. If a file has multiple tags, the one with the highest priority colors the file",
  ADD_RULE_BTN: "Add general rule",
  ADD_FOLDER_RULE_BTN: "Add folder rule",
  TAG_PLACEHOLDER: "Enter a tag (case-insensitive)",
  DUPLICATE_TAG_ERROR: "Warning: at least two conflicting rules created for one tag! Choose another tag.",
  INVALID_TAG_ERROR: "Invalid tag name",
  OPERATOR_CONTAINS: "contains",
  OPERATOR_NOT_CONTAINS: "does not contain",
  FILTER_FOLDER_PLACEHOLDER: "Start typing folder name\u2026"
};

// locales/ru.ts
var ru_default = {
  SETTINGS_TITLE: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Tags Color Files",
  PLUGIN_DESCRIPTION: "\u0414\u0430\u043D\u043D\u044B\u0439 \u043F\u043B\u0430\u0433\u0438\u043D \u043F\u043E\u0437\u0432\u043E\u043B\u044F\u0435\u0442 \u0432\u044B\u0434\u0435\u043B\u044F\u0442\u044C \u0444\u0430\u0439\u043B\u044B \u0432 \u043F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A\u0435 Obsidian \u0441\u043E\u0433\u043B\u0430\u0441\u043D\u043E \u0437\u0430\u0434\u0430\u043D\u043D\u044B\u043C \u0432\u0430\u043C\u0438 \u043F\u0440\u0430\u0432\u0438\u043B\u0430\u043C \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F. \u041F\u0440\u0438 \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0438\u0438 \u043A \u0444\u0430\u0439\u043B\u0443 \u0442\u0435\u0433\u0430, \u0434\u043B\u044F \u043A\u043E\u0442\u043E\u0440\u043E\u0433\u043E \u0441\u043E\u0437\u0434\u0430\u043D\u043E \u043F\u0440\u0430\u0432\u0438\u043B\u043E, \u043F\u043B\u0430\u0433\u0438\u043D \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u0442 \u0435\u0433\u043E \u0432 \u0441\u043E\u043E\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u044E\u0449\u0438\u0439 \u0446\u0432\u0435\u0442 \u0432 \u043F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A\u0435 \u0432 \u0432\u044B\u0431\u0440\u0430\u043D\u043D\u043E\u043C \u0432\u0430\u043C\u0438 \u0441\u0442\u0438\u043B\u0435.",
  GENERAL_SECTION: "\u041E\u0441\u043D\u043E\u0432\u043D\u044B\u0435",
  COLOR_METHOD_NAME: "\u0421\u043F\u043E\u0441\u043E\u0431 \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F",
  COLOR_METHOD_DESC: '\u0415\u0441\u043B\u0438 \u0432\u044B\u0431\u0440\u0430\u043D \u043E\u0434\u0438\u043D \u0438\u0437 \u0441\u043F\u043E\u0441\u043E\u0431\u043E\u0432 \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F "\u0422\u043E\u0447\u043A\u0438...", \u0434\u043E \u0442\u0440\u0451\u0445 \u0446\u0432\u0435\u0442\u043D\u044B\u0445 \u0442\u043E\u0447\u0435\u043A \u0431\u0443\u0434\u0435\u0442 \u043E\u0434\u043D\u043E\u0432\u0440\u0435\u043C\u0435\u043D\u043D\u043E \u043E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0442\u044C\u0441\u044F, \u0435\u0441\u043B\u0438 \u0432 \u0444\u0430\u0439\u043B\u0435 \u0441\u043E\u0434\u0435\u0440\u0436\u0438\u0442\u0441\u044F \u0431\u043E\u043B\u044C\u0448\u0435 \u043E\u0434\u043D\u043E\u0433\u043E \u0442\u0435\u0433\u0430, \u0434\u043B\u044F \u043A\u043E\u0442\u043E\u0440\u043E\u0433\u043E \u0441\u043E\u0437\u0434\u0430\u043D\u043E \u043F\u0440\u0430\u0432\u0438\u043B\u043E \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F.',
  COLOR_TEXT: "\u0422\u0435\u043A\u0441\u0442",
  COLOR_BG: "\u0424\u043E\u043D",
  COLOR_DOTS_BEFORE: "\u0422\u043E\u0447\u043A\u0438 \u043F\u0435\u0440\u0435\u0434 \u0442\u0435\u043A\u0441\u0442\u043E\u043C",
  COLOR_DOTS_AFTER: "\u0422\u043E\u0447\u043A\u0438 \u043F\u043E\u0441\u043B\u0435 \u0442\u0435\u043A\u0441\u0442\u0430",
  COLOR_DOTS_BEFORE_TEXT: "\u0422\u043E\u0447\u043A\u0438 \u043F\u0435\u0440\u0435\u0434 \u0442\u0435\u043A\u0441\u0442\u043E\u043C + \u0442\u0435\u043A\u0441\u0442",
  COLOR_DOTS_AFTER_TEXT: "\u0422\u043E\u0447\u043A\u0438 \u043F\u043E\u0441\u043B\u0435 \u0442\u0435\u043A\u0441\u0442\u0430 + \u0442\u0435\u043A\u0441\u0442",
  BACKUP_RESTORE: "\u0420\u0435\u0437\u0435\u0440\u0432\u043D\u043E\u0435 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u0438 \u0432\u043E\u0441\u0441\u0442\u0430\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435",
  DOT_SIZE_NAME: "\u0420\u0430\u0437\u043C\u0435\u0440 \u0442\u043E\u0447\u0435\u043A",
  DOT_SIZE_DESC: '\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0440\u0430\u0437\u043C\u0435\u0440 \u0446\u0432\u0435\u0442\u043D\u044B\u0445 \u0442\u043E\u0447\u0435\u043A \u0434\u043B\u044F \u043C\u0435\u0442\u043E\u0434\u043E\u0432 \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F "\u0422\u043E\u0447\u043A\u0438..."',
  DOT_SMALL: "\u041C\u0430\u043B\u0435\u043D\u044C\u043A\u0438\u0435",
  DOT_DEFAULT: "\u041F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
  DOT_BIG: "\u0411\u043E\u043B\u044C\u0448\u0438\u0435",
  EXPORT: "\u042D\u043A\u0441\u043F\u043E\u0440\u0442 \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043A",
  IMPORT: "\u0418\u043C\u043F\u043E\u0440\u0442 \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043A",
  EXPORTED: "\u0423\u0441\u043F\u0435\u0448\u043D\u043E \u044D\u043A\u0441\u043F\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u043E!",
  IMPORTED: "\u0423\u0441\u043F\u0435\u0448\u043D\u043E \u0438\u043C\u043F\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u043E!",
  INVALID_FILE: "\u041E\u0448\u0438\u0431\u043A\u0430: \u041D\u0435\u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\u044B\u0439 \u0444\u0430\u0439\u043B",
  COLORING_RULES_SECTION: "\u041F\u0440\u0430\u0432\u0438\u043B\u0430 \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u043D\u0438\u044F",
  ADD_RULE_DESC: "\u041E\u0431\u0449\u0438\u0435 \u043F\u0440\u0430\u0432\u0438\u043B\u0430 \u043F\u0440\u0438\u043C\u0435\u043D\u044F\u044E\u0442\u0441\u044F \u043A\u043E \u0432\u0441\u0435\u043C \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C \u0432 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0435, \u043F\u0440\u0430\u0432\u0438\u043B\u0430 \u043F\u0430\u043F\u043E\u043A \u043F\u0440\u0438\u043C\u0435\u043D\u044F\u044E\u0442\u0441\u044F \u0442\u043E\u043B\u044C\u043A\u043E \u043A \u0444\u0430\u0439\u043B\u0430\u043C \u0432\u043D\u0443\u0442\u0440\u0438 \u0432\u044B\u0431\u0440\u0430\u043D\u043D\u043E\u0439 \u043F\u0430\u043F\u043A\u0438. \u0415\u0441\u043B\u0438 \u0444\u0430\u0439\u043B \u0438\u043C\u0435\u0435\u0442 \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0442\u0435\u0433\u043E\u0432, \u0435\u0433\u043E \u043E\u043A\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u0442 \u043D\u0430\u0438\u0431\u043E\u043B\u0435\u0435 \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442\u043D\u043E\u0435 \u043F\u0440\u0430\u0432\u0438\u043B\u043E",
  ADD_RULE_BTN: "\u041D\u043E\u0432\u043E\u0435 \u043E\u0431\u0449\u0435\u0435 \u043F\u0440\u0430\u0432\u0438\u043B\u043E",
  ADD_FOLDER_RULE_BTN: "\u041D\u043E\u0432\u043E\u0435 \u043F\u0440\u0430\u0432\u0438\u043B\u043E \u043F\u0430\u043F\u043A\u0438",
  TAG_PLACEHOLDER: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\u0433 (\u0440\u0435\u0433\u0438\u0441\u0442\u0440 \u043D\u0435 \u0443\u0447\u0438\u0442\u044B\u0432\u0430\u0435\u0442\u0441\u044F)",
  DUPLICATE_TAG_ERROR: "\u0412\u043D\u0438\u043C\u0430\u043D\u0438\u0435: \u041F\u043E \u043A\u0440\u0430\u0439\u043D\u0435\u0439 \u043C\u0435\u0440\u0435 \u0434\u0432\u0430 \u043A\u043E\u043D\u0444\u043B\u0438\u043A\u0442\u0443\u044E\u0449\u0438\u0445 \u043F\u0440\u0430\u0432\u0438\u043B\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u044B \u0434\u043B\u044F \u043E\u0434\u043D\u043E\u0433\u043E \u0442\u0435\u0433\u0430! \u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0434\u0440\u0443\u0433\u043E\u0439 \u0442\u0435\u0433",
  INVALID_TAG_ERROR: "\u041D\u0435\u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\u043E\u0435 \u0438\u043C\u044F \u0442\u0435\u0433\u0430",
  OPERATOR_CONTAINS: "\u0441\u043E\u0434\u0435\u0440\u0436\u0438\u0442",
  OPERATOR_NOT_CONTAINS: "\u043D\u0435 \u0441\u043E\u0434\u0435\u0440\u0436\u0438\u0442",
  FILTER_FOLDER_PLACEHOLDER: "\u041D\u0430\u0447\u043D\u0438\u0442\u0435 \u0432\u0432\u043E\u0434\u0438\u0442\u044C \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0430\u043F\u043A\u0438\u2026"
};

// locales-list.ts
var localeMap = {
  en: en_default,
  ru: ru_default
  // Add other mappings here
};
var t = (key) => {
  const lang = import_obsidian.moment.locale();
  const targetLocale = localeMap[lang] || localeMap.en;
  return targetLocale[key] || localeMap.en[key] || key;
};

// main.ts
var TagSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const cache = this.app.metadataCache;
    const allTags = Object.keys(cache.getTags());
    const normalizedQuery = query.startsWith("#") ? query.toLowerCase() : `#${query.toLowerCase()}`;
    return allTags.filter((tag) => tag.toLowerCase().contains(normalizedQuery));
  }
  renderSuggestion(tag, el) {
    el.setText(tag);
  }
  selectSuggestion(tag) {
    this.inputEl.value = tag;
    this.inputEl.trigger("input");
    this.close();
  }
};
var FolderSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    return this.app.vault.getAllFolders(false).map((f) => f.path).filter((p) => p.toLowerCase().contains(lowerQuery));
  }
  renderSuggestion(path, el) {
    el.setText(path);
  }
  selectSuggestion(path) {
    this.inputEl.value = path;
    this.inputEl.trigger("input");
    this.close();
  }
};
var DEFAULT_SETTINGS = {
  generalRules: [],
  colorStrategy: "text",
  dotSize: "default"
};
var TagsColorFilesPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.updateFileColors = (0, import_obsidian2.debounce)(() => this._updateFileColors(), 50, true);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TagsColorFilesSettingTab(this.app, this));
    this.registerEvent(
      this.app.metadataCache.on("changed", () => this.updateFileColors())
    );
    this.registerEvent(
      this.app.vault.on("rename", () => this.updateFileColors())
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.updateFileColors())
    );
    this.observer = new MutationObserver((mutations) => {
      let shouldUpdate = false;
      for (const m of mutations) {
        for (const node of Array.from(m.addedNodes)) {
          if (node.nodeType === Node.ELEMENT_NODE && (node.classList.contains("nav-file") || node.querySelector(".nav-file-title"))) {
            shouldUpdate = true;
            break;
          }
        }
        if (shouldUpdate) break;
      }
      if (shouldUpdate) this.updateFileColors();
    });
    this.app.workspace.onLayoutReady(() => {
      this.observer.observe(activeDocument.body, {
        childList: true,
        subtree: true
      });
      window.setTimeout(() => this.updateFileColors(), 500);
    });
  }
  onunload() {
    if (this.observer) this.observer.disconnect();
    this.removeFileColors();
  }
  async loadSettings() {
    const raw = await this.loadData();
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      raw
    );
  }
  async saveSettings() {
    this.settings.generalRules = this.settings.generalRules.filter(
      (r) => r.tag && r.tag.trim() !== ""
    );
    await this.saveData(this.settings);
    this.updateFileColors();
  }
  removeFileColors() {
    const fileExplorers = this.app.workspace.getLeavesOfType("file-explorer");
    fileExplorers.forEach((leaf) => {
      leaf.view.containerEl.querySelectorAll(".nav-file-title").forEach((el) => this.cleanElement(el));
    });
  }
  cleanElement(el) {
    el.classList.remove(
      "colored-tag-file",
      "strategy-text",
      "strategy-background",
      "strategy-before-text",
      "strategy-after-text",
      "strategy-dots-before-text",
      "strategy-dots-after-text"
    );
    el.style.removeProperty("--tag-file-color");
    const existingDots = el.querySelector(".tag-dots-container");
    if (existingDots) existingDots.remove();
  }
  _updateFileColors() {
    const fileExplorers = this.app.workspace.getLeavesOfType("file-explorer");
    const normalizedRules = this.settings.generalRules.filter((c) => c.tag).map((c) => {
      var _a;
      return {
        ...c,
        _normalized: c.tag.replace(/^#/, "").toLowerCase(),
        _folderScope: ((_a = c.folderScope) != null ? _a : "").trim()
      };
    });
    fileExplorers.forEach((leaf) => {
      const navFiles = leaf.view.containerEl.querySelectorAll(".nav-file-title");
      navFiles.forEach((el) => {
        var _a, _b, _c;
        const path = el.getAttribute("data-path");
        if (!path) return;
        const file = this.app.vault.getAbstractFileByPath(path);
        if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") return;
        const cache = this.app.metadataCache.getFileCache(file);
        const fileTags = cache ? (_a = (0, import_obsidian2.getAllTags)(cache)) != null ? _a : [] : [];
        this.cleanElement(el);
        const fileFolder = (_c = (_b = file.parent) == null ? void 0 : _b.path) != null ? _c : "";
        const matchedColors = [];
        for (const rule of normalizedRules) {
          if (rule._folderScope) {
            const inScope = fileFolder === rule._folderScope || fileFolder.startsWith(rule._folderScope + "/");
            if (!inScope) continue;
          }
          const hasTag = fileTags.some(
            (tag) => tag.replace(/^#/, "").toLowerCase() === rule._normalized
          );
          if (rule.isNegative ? !hasTag : hasTag) {
            matchedColors.push(rule.color);
          }
        }
        if (matchedColors.length > 0) {
          el.classList.add("colored-tag-file");
          el.classList.add(`strategy-${this.settings.colorStrategy}`);
          el.style.setProperty("--tag-file-color", matchedColors[0]);
          const strategiesWithDots = [
            "before-text",
            "after-text",
            "dots-before-text",
            "dots-after-text"
          ];
          if (strategiesWithDots.includes(this.settings.colorStrategy)) {
            const dotsContainer = createDiv();
            const hasNavFileParent = !!el.closest("div.nav-folder");
            const isBefore = this.settings.colorStrategy.includes("before-text");
            const positionClass = isBefore ? hasNavFileParent ? "is-before" : "is-before-root" : "is-after";
            dotsContainer.className = `tag-dots-container ${positionClass} dots-${this.settings.dotSize}`;
            matchedColors.slice(0, 3).forEach((color, i) => {
              const dot = createDiv();
              dot.className = "tag-dot";
              dot.style.setProperty("--dot-color", color);
              dot.style.setProperty("--dot-index", i.toString());
              dotsContainer.appendChild(dot);
            });
            el.appendChild(dotsContainer);
          }
        }
      });
    });
  }
};
var TagsColorFilesSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.draggingGroupIdx = null;
    this.draggingRuleIdx = null;
    this.focusPending = null;
    this.ruleElements = [];
    this.errorBanner = null;
    this.renderRoot = null;
    this.plugin = plugin;
  }
  validateTagName(tag) {
    if (!tag) return true;
    const cleanTag = tag.replace(/^#/, "");
    if (!cleanTag) return true;
    const validTagRegex = /^(?!\d+$)[\p{L}\p{N}/_-]+$/u;
    return validTagRegex.test(cleanTag);
  }
  validateGroupTags(groupIdx) {
    var _a, _b, _c, _d;
    const groupRuleEls = this.ruleElements.filter(
      (e) => e.groupIdx === groupIdx
    );
    const tagCounts = {};
    for (const el of groupRuleEls) {
      const tag = el.txt.value.replace(/^#/, "").toLowerCase().trim();
      const scope = ((_b = (_a = el.folderInput) == null ? void 0 : _a.value) != null ? _b : "").trim().toLowerCase();
      if (tag) tagCounts[`${tag}::${scope}`] = (tagCounts[`${tag}::${scope}`] || 0) + 1;
    }
    let firstError = null;
    for (const el of groupRuleEls) {
      const rawVal = el.txt.value.trim();
      const normalizedVal = rawVal.replace(/^#/, "").toLowerCase();
      const scope = ((_d = (_c = el.folderInput) == null ? void 0 : _c.value) != null ? _d : "").trim().toLowerCase();
      const isDuplicate = normalizedVal && tagCounts[`${normalizedVal}::${scope}`] > 1;
      const isValid = this.validateTagName(rawVal);
      if (isDuplicate || !isValid) {
        el.txt.addClass("is-invalid");
        firstError != null ? firstError : firstError = !isValid ? t("INVALID_TAG_ERROR") : t("DUPLICATE_TAG_ERROR");
      } else {
        el.txt.removeClass("is-invalid");
      }
    }
    if (this.errorBanner) {
      if (firstError !== null) {
        this.errorBanner.setText(firstError);
        this.errorBanner.addClass("is-visible");
      } else {
        this.errorBanner.removeClass("is-visible");
      }
    }
  }
  /**
   * Render a single rule row (+ its collapsible filter panel) into `container`.
   * groupIdx is always -1 (single general-rules section).
   */
  renderRuleRow(container, config, ruleIdx, groupIdx, rulesArray) {
    var _a;
    const div = container.createDiv({ cls: "tag-color-setting-item" });
    const txt = createEl("input");
    txt.type = "text";
    txt.value = config.tag;
    txt.placeholder = t("TAG_PLACEHOLDER");
    if (import_obsidian2.Platform.isMobile) {
      const reorderContainer = div.createDiv({ cls: "tag-reorder-arrows" });
      const upBtn = reorderContainer.createEl("button", {
        cls: "clickable-icon"
      });
      (0, import_obsidian2.setIcon)(upBtn, "arrow-up");
      upBtn.onclick = () => {
        if (ruleIdx > 0) {
          const moved = rulesArray.splice(ruleIdx, 1)[0];
          rulesArray.splice(ruleIdx - 1, 0, moved);
          void this.plugin.saveSettings();
          this.rerender();
        }
      };
      const downBtn = reorderContainer.createEl("button", {
        cls: "clickable-icon"
      });
      (0, import_obsidian2.setIcon)(downBtn, "arrow-down");
      downBtn.onclick = () => {
        if (ruleIdx < rulesArray.length - 1) {
          const moved = rulesArray.splice(ruleIdx, 1)[0];
          rulesArray.splice(ruleIdx + 1, 0, moved);
          void this.plugin.saveSettings();
          this.rerender();
        }
      };
    } else {
      if (this.draggingGroupIdx === groupIdx && this.draggingRuleIdx === ruleIdx) {
        div.addClass("is-dragging");
      }
      div.draggable = true;
      const dragHandle = div.createDiv({ cls: "clickable-icon drag-handle" });
      (0, import_obsidian2.setIcon)(dragHandle, "lucide-grip-vertical");
      div.addEventListener("dragstart", () => {
        this.validateGroupTags(groupIdx);
        if (!txt.classList.contains("is-invalid") && txt.value.trim() !== "") {
          config.tag = txt.value;
        }
        this.draggingGroupIdx = groupIdx;
        this.draggingRuleIdx = ruleIdx;
        div.addClass("is-dragging");
      });
      div.addEventListener("dragend", () => {
        this.draggingGroupIdx = null;
        this.draggingRuleIdx = null;
        div.removeClass("is-dragging");
        this.rerender();
      });
      div.addEventListener("dragover", (e) => {
        e.preventDefault();
        if (this.draggingGroupIdx === groupIdx && this.draggingRuleIdx !== null && this.draggingRuleIdx !== ruleIdx) {
          const moved = rulesArray.splice(this.draggingRuleIdx, 1)[0];
          rulesArray.splice(ruleIdx, 0, moved);
          this.draggingRuleIdx = ruleIdx;
          void this.plugin.saveSettings();
          this.rerender();
        }
      });
    }
    const cp = createEl("input");
    cp.type = "color";
    cp.value = config.color;
    cp.addClass("tag-color-picker-input");
    cp.onchange = (e) => {
      config.color = e.target.value;
      void this.plugin.saveSettings();
    };
    div.appendChild(cp);
    const operatorBtn = div.createDiv({
      cls: "combobox-button filter-operator",
      attr: { tabindex: "0" }
    });
    operatorBtn.createDiv({ cls: "combobox-button-icon" });
    const operatorLabel = operatorBtn.createDiv({ cls: "combobox-button-label" });
    operatorLabel.setText(
      config.isNegative ? t("OPERATOR_NOT_CONTAINS") : t("OPERATOR_CONTAINS")
    );
    const operatorClearEl = operatorBtn.createDiv({ cls: "combobox-clear-button" });
    (0, import_obsidian2.setIcon)(operatorClearEl, "lucide-x");
    const operatorChevronEl = operatorBtn.createDiv({ cls: "combobox-button-chevron" });
    (0, import_obsidian2.setIcon)(operatorChevronEl, "lucide-chevrons-up-down");
    operatorBtn.addEventListener("click", (e) => {
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (item) => item.setTitle(t("OPERATOR_CONTAINS")).setChecked(!config.isNegative).onClick(() => {
          config.isNegative = false;
          operatorLabel.setText(t("OPERATOR_CONTAINS"));
          void this.plugin.saveSettings();
        })
      );
      menu.addItem(
        (item) => item.setTitle(t("OPERATOR_NOT_CONTAINS")).setChecked(!!config.isNegative).onClick(() => {
          config.isNegative = true;
          operatorLabel.setText(t("OPERATOR_NOT_CONTAINS"));
          void this.plugin.saveSettings();
        })
      );
      const rect = operatorBtn.getBoundingClientRect();
      menu.showAtPosition({ x: rect.left, y: rect.bottom });
    });
    const inputContainer = div.createDiv({ cls: "tag-input-container" });
    const fieldWrapper = inputContainer.createDiv({
      cls: "tag-input-field-wrapper"
    });
    fieldWrapper.appendChild(txt);
    new TagSuggest(this.app, txt);
    let folderInput = null;
    if (config.folderScope !== void 0) {
      folderInput = inputContainer.createEl("input");
      const fi = folderInput;
      fi.type = "text";
      fi.value = (_a = config.folderScope) != null ? _a : "";
      fi.placeholder = t("FILTER_FOLDER_PLACEHOLDER");
      fi.addClass("tag-folder-scope-input");
      new FolderSuggest(this.app, fi);
      const debouncedFolderSave = (0, import_obsidian2.debounce)(
        async () => {
          config.folderScope = fi.value.trim();
          await this.plugin.saveSettings();
        },
        400,
        true
      );
      fi.oninput = () => {
        this.validateGroupTags(groupIdx);
        debouncedFolderSave();
      };
      fi.onchange = (e) => {
        config.folderScope = e.target.value.trim();
        this.validateGroupTags(groupIdx);
        void this.plugin.saveSettings();
      };
    }
    const debouncedSave = (0, import_obsidian2.debounce)(
      async () => {
        if (txt.value.trim() !== "") {
          config.tag = txt.value;
          await this.plugin.saveSettings();
        }
      },
      400,
      true
    );
    txt.oninput = () => {
      this.validateGroupTags(groupIdx);
      debouncedSave();
    };
    txt.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.validateGroupTags(groupIdx);
        if (!txt.classList.contains("is-invalid")) {
          config.tag = txt.value;
          void this.plugin.saveSettings();
          txt.blur();
        }
      }
    });
    txt.onchange = (e) => {
      config.tag = e.target.value;
      this.validateGroupTags(groupIdx);
      void this.plugin.saveSettings();
    };
    txt.addEventListener("blur", () => {
      if (!txt.value || txt.value.trim() === "") {
        rulesArray.splice(ruleIdx, 1);
        void this.plugin.saveSettings();
        this.rerender();
      }
    });
    const del = div.createEl("button", { cls: "clickable-icon" });
    (0, import_obsidian2.setIcon)(del, "trash");
    del.onclick = () => {
      rulesArray.splice(ruleIdx, 1);
      void this.plugin.saveSettings();
      this.rerender();
    };
    this.ruleElements.push({ txt, folderInput, groupIdx });
  }
  getSettingDefinitions() {
    return [
      {
        type: "group",
        cls: "tags-color-files-settings-group",
        items: [
          {
            // `name`/`desc`/`aliases` feed the settings search index; the row's
            // own label markup is hidden in CSS because renderBody() draws its
            // own heading and description.
            name: t("SETTINGS_TITLE"),
            desc: t("PLUGIN_DESCRIPTION"),
            aliases: [
              "tag",
              "tags",
              "color",
              "colors",
              "coloring",
              "colour",
              "file explorer",
              "highlight",
              "rules",
              "coloring rules",
              "folder rule",
              "general rule",
              "text",
              "background",
              "dots",
              "dots size",
              "backup",
              "restore",
              "import",
              "export"
            ],
            render: (setting) => {
              setting.settingEl.addClass("tags-color-files-settings-anchor");
              const existing = setting.settingEl.querySelector(
                ":scope > .tags-color-files-settings-root"
              );
              this.renderBody(
                existing != null ? existing : setting.settingEl.createDiv(
                  "tags-color-files-settings-root"
                )
              );
              return () => {
                this.renderRoot = null;
                this.ruleElements = [];
                this.errorBanner = null;
                this.draggingGroupIdx = null;
                this.draggingRuleIdx = null;
              };
            }
          }
        ]
      }
    ];
  }
  /** Nearest scrollable ancestor — the settings pane on desktop, the tab
   *  container on phones. */
  findScrollContainer(el) {
    for (let p = el.parentElement; p; p = p.parentElement) {
      const overflowY = p.win.getComputedStyle(p).overflowY;
      if ((overflowY === "auto" || overflowY === "scroll") && p.scrollHeight > p.clientHeight) {
        return p;
      }
    }
    return null;
  }
  /**
   * Re-render the plugin's own root rather than calling `update()`, which would
   * re-reconcile Obsidian's definition list.
   *
   * renderBody() empties the root, which collapses the scroll container's
   * scrollHeight and makes the browser clamp its scrollTop to 0. Capture and
   * restore it so a re-render (reordering a rule by drag, deleting one, …)
   * leaves the view where the user left it instead of jumping to the top.
   */
  rerender() {
    var _a;
    if (!this.renderRoot) return;
    const scroller = this.focusPending === null ? this.findScrollContainer(this.renderRoot) : null;
    const scrollTop = (_a = scroller == null ? void 0 : scroller.scrollTop) != null ? _a : 0;
    this.renderBody(this.renderRoot);
    if (scroller) scroller.scrollTop = scrollTop;
  }
  renderBody(root) {
    this.renderRoot = root;
    root.empty();
    this.ruleElements = [];
    new import_obsidian2.Setting(root).setName(t("SETTINGS_TITLE")).setHeading();
    const descContainer = root.createDiv({
      cls: "plugin-description-container"
    });
    descContainer.createEl("p", {
      text: t("PLUGIN_DESCRIPTION"),
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(root).setName(t("GENERAL_SECTION")).setHeading();
    new import_obsidian2.Setting(root).setName(t("COLOR_METHOD_NAME")).setDesc(t("COLOR_METHOD_DESC")).addDropdown((dropdown) => {
      dropdown.addOption("text", t("COLOR_TEXT")).addOption("background", t("COLOR_BG")).addOption("before-text", t("COLOR_DOTS_BEFORE")).addOption("after-text", t("COLOR_DOTS_AFTER")).addOption("dots-before-text", t("COLOR_DOTS_BEFORE_TEXT")).addOption("dots-after-text", t("COLOR_DOTS_AFTER_TEXT")).setValue(this.plugin.settings.colorStrategy).onChange(async (value) => {
        this.plugin.settings.colorStrategy = value;
        await this.plugin.saveSettings();
        this.rerender();
      });
    });
    const strategiesWithDots = [
      "before-text",
      "after-text",
      "dots-before-text",
      "dots-after-text"
    ];
    if (strategiesWithDots.includes(this.plugin.settings.colorStrategy)) {
      new import_obsidian2.Setting(root).setName(t("DOT_SIZE_NAME")).setDesc(t("DOT_SIZE_DESC")).addDropdown((dropdown) => {
        dropdown.addOption("small", t("DOT_SMALL")).addOption("default", t("DOT_DEFAULT")).addOption("big", t("DOT_BIG")).setValue(this.plugin.settings.dotSize).onChange(async (value) => {
          this.plugin.settings.dotSize = value;
          await this.plugin.saveSettings();
        });
      });
    }
    const backupSetting = new import_obsidian2.Setting(root).setName(t("BACKUP_RESTORE"));
    if (!import_obsidian2.Platform.isMobile) {
      backupSetting.addButton(
        (btn) => btn.setButtonText(t("EXPORT")).onClick(() => {
          const data = JSON.stringify(
            { generalRules: this.plugin.settings.generalRules },
            null,
            2
          );
          const blob = new Blob([data], { type: "application/json" });
          const url = URL.createObjectURL(blob);
          const a = activeDocument.body.createEl("a", {
            href: url,
            attr: { download: "data.json" }
          });
          a.click();
          a.detach();
          URL.revokeObjectURL(url);
          new import_obsidian2.Notice(t("EXPORTED"));
        })
      );
    }
    backupSetting.addButton(
      (btn) => btn.setButtonText(t("IMPORT")).onClick(() => {
        const input = createEl("input");
        input.type = "file";
        input.accept = ".json";
        input.onchange = (e) => {
          var _a;
          const target = e.target;
          const file = (_a = target.files) == null ? void 0 : _a[0];
          if (!file) return;
          const reader = new FileReader();
          reader.onload = (event) => {
            var _a2;
            try {
              const result = (_a2 = event.target) == null ? void 0 : _a2.result;
              if (typeof result === "string") {
                const parsed = JSON.parse(result);
                if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed) && "generalRules" in parsed) {
                  const obj = parsed;
                  this.plugin.settings.generalRules = Array.isArray(obj.generalRules) ? obj.generalRules : [];
                  void this.plugin.saveSettings();
                  this.rerender();
                  new import_obsidian2.Notice(t("IMPORTED"));
                  return;
                }
                new import_obsidian2.Notice(t("INVALID_FILE"));
              }
            } catch (e2) {
              new import_obsidian2.Notice(t("INVALID_FILE"));
            }
          };
          reader.readAsText(file);
        };
        input.click();
      })
    );
    new import_obsidian2.Setting(root).setName(t("COLORING_RULES_SECTION")).setHeading();
    new import_obsidian2.Setting(root).setClass("tag-add-rule-setting").setDesc(t("ADD_RULE_DESC")).addButton((btn) => {
      (0, import_obsidian2.setIcon)(btn.buttonEl, "lucide-folder");
      btn.buttonEl.createSpan({ text: t("ADD_FOLDER_RULE_BTN") });
      btn.onClick(() => {
        this.plugin.settings.generalRules.unshift({
          tag: "",
          color: "#4a90e2",
          folderScope: ""
        });
        this.focusPending = -1;
        this.rerender();
      });
    }).addButton((btn) => {
      (0, import_obsidian2.setIcon)(btn.buttonEl, "lucide-tag");
      btn.buttonEl.createSpan({ text: t("ADD_RULE_BTN") });
      btn.onClick(() => {
        this.plugin.settings.generalRules.unshift({
          tag: "",
          color: "#4a90e2"
        });
        this.focusPending = -1;
        this.rerender();
      });
    });
    this.errorBanner = root.createDiv({ cls: "tag-error-message" });
    const generalRulesContainer = root.createDiv({
      cls: "tag-rules-list"
    });
    this.plugin.settings.generalRules.forEach((config, ruleIdx) => {
      this.renderRuleRow(
        generalRulesContainer,
        config,
        ruleIdx,
        -1,
        this.plugin.settings.generalRules
      );
    });
    if (this.focusPending !== null) {
      this.focusPending = null;
      const target = this.ruleElements.find((e) => e.groupIdx === -1);
      target == null ? void 0 : target.txt.focus();
    }
    this.validateGroupTags(-1);
  }
};

/* nosourcemap */